notifications:
  email: false
  
language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten-ubuntu bash

script:
  - docker exec emscripten bash -c "apt-get update;apt-get install file -y;make"


